### ISSUE TITLE
Consume HashObject in ssz and new array method

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/ssz#156]
**Motivation**
1. HashObject

+ The new as-sha256 and persistent-merkle-tree implementation uses HashObject internally, we need to expose that
+ ssz would use it to probably extract/set value faster (for uint type) without having to use an intermediate Uint8Array

2. In order to update an array (list/vector) the consumer has to get array item, +/-delta and update back the item to the array
```ts
   state.balances[i] = state.balances[i] + delta;
```
we should be able to implement a new "`tree_`" method in the array like
```ts
  tree_updateUint64Delta(index: number, delta: number): number;
```
it'd save 1 time to access/traverse the tree.

**Comment by dapplion** [comment]
Note that maybe we have to already read balances into a flat array for faster iteration. So we may only have to do a single write. But that should be reviewed and discussed in the lodestar repo

**Comment by tuyennhv** [comment]
> Note that maybe we have to already read balances into a flat array for faster iteration. So we may only have to do a single write. But that should be reviewed and discussed in the lodestar repo

my understanding from the last conversation is we only need to track effectiveBalances, not balances. What I see from the spec is balances is not involved in any calculation, currently we only cache it because we don't have this "applyDelta" apis in this issue.

@dapplion if this is a confusion, please open an issue in lodestar.

**Comment by dapplion** [comment]
Right, outside of the epoch transition we will only have access to effectiveBalances. But during epoch transition we can compute a flat balances array in epoch process.

**Comment by tuyennhv** [comment]
@dapplion the `applyDeltas` method does return new balances array so we don't have to extract again https://github.com/ChainSafe/ssz/pull/159/files#diff-cc83a6a805408a86b830e8871f2baf9929235bd7ab282351b59a1f66b25fb76dR63

it'll then be assigned to `epochProcess` and we'll use it in `processEffectiveBalances()`
