### ISSUE TITLE
statically providing casingMap while creating a new container type.

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/ssz#195]
While figuring out a way to provide case transformation in the container datafill (toJson/fromJson calls), it was brainstormed that other elegant solution will be a way provide an optional casingMap while declaring the container (which can not only be used to case transform custom fields but as well as as speedup the normal fields lookup) and will also work well in the nested containers scenario having different casing of the fields.

**Is your feature request related to a problem? Please describe.**
case transformation of fields while filling/extracting container data from/to json.

**Describe the solution you'd like**
Declaring the casing structure of the fields while we create a container type.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/76567250/133231359-947c7741-0670-4345-9370-860cdefde488.png)

**Comment by g11tech** [comment]
@dapplion @wemeetagain  how does this example  looks for providing the declaration time casingMap
```
const SlashingTransformFieldObject = new ContainerType({
  fields: {
    eth1Data: new NumberUintType({byteLength: 4}),
    signedHeader1: new NumberUintType({byteLength: 4}),
    signedHeader2: new NumberUintType({byteLength: 4}),
    attestation1: new BooleanType(),
    attestation2: new BooleanType(),
  },
  casingMap: {
    eth1Data: {default:"camel", snake: "eth1_data", ...},
    attestation1: {snake: "attestation_1"} 
  }
});
```
if there is a snake conversion (or default snake) provided and a casing has to be derived (not present in the casingMap), it can be used to chunkify and transform correctly.

also another question pops to mind, if a dynamic casing happens via toJson/fromJson, should we allow a flag to cache it so that next time around it just picks from the cache?

**Comment by dapplion** [comment]
@g11tech I would keep it simple

```ts
const SlashingTransformFieldObject = new ContainerType({
  fields: {
    eth1Data: new NumberUintType({byteLength: 4}),
    signedHeader1: new NumberUintType({byteLength: 4}),
    signedHeader2: new NumberUintType({byteLength: 4}),
    attestation1: new BooleanType(),
    attestation2: new BooleanType(),
  },
  casingMap: {
    eth1Data: "eth1_data",
    attestation1: "attestation_1"
    ...
  }
});
```

Casing map provides the "correct" casing regardless of the name. If that's provided that's what has to be used ignoring any other option

**Comment by g11tech** [comment]
@dapplion  yes but what if the toJSON call comes with case as "constant"? type declaration time casingMap declaration can't assume "correct" casing, imho.

**Comment by dapplion** [comment]
> @dapplion yes but what if the toJSON call comes with case as "constant"? type declaration time casingMap declaration can't assume "correct" casing, imho.
> If we do this, we will be "fixing" the json keys of toJson/fromJson of the fields provided in casingMap (unless toJson and fromJson don't provide their own overriding casingMap).
> which will work just fine for purposes of lodestar client/server api data.

Let's assume casingMap is correct for now. We need this change now to be compatible with the eth2 specs. If this is a problem for UX let's figure it out in another PR please

**Comment by g11tech** [comment]
> > @dapplion yes but what if the toJSON call comes with case as "constant"? type declaration time casingMap declaration can't assume "correct" casing, imho.
> > If we do this, we will be "fixing" the json keys of toJson/fromJson of the fields provided in casingMap (unless toJson and fromJson don't provide their own overriding casingMap).
> > which will work just fine for purposes of lodestar client/server api data.
> 
> Let's assume casingMap is correct for now. We need this change now to be compatible with the eth2 specs. If this is a problem for UX let's figure it out in another PR please

that compatibility can be even done from the previous merge by providing jsonOpts map, should I send a draft PR for the same?

**Comment by g11tech** [comment]
this PR already solved the api case mismatch but got `MERGE_FORK_VERSION` filed missing error as the lighthouse config api had not yet had that field in their response (can update to their latest stable and check again)

https://github.com/ChainSafe/lodestar/pull/3086/files
