### ISSUE TITLE
mono repo release workflow

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/ssz#203]
the current release workflow is failing post monorepo structure change.

1. changelog step is giving issue with the pre monorepo tags created - suggestion delete them (verified in my  forked clone of account)  https://github.com/ChainSafe/ssz/pull/201#issuecomment-930390619

2. release version number is being picked from packages/ssz/package.json, its currently 0.8.18, but there are tags imported from other repos as consequence of merge like 0.19... So should we do the tagging with 0.20. something?
3. since the other packages are on different versions, should be track the release version and tag from the main package.json? that version will be required to be incremented each time a child package needs publishing. in lodestar we update versions of all packages

**Comment by g11tech** [comment]
@dapplion @wemeetagain

**Comment by wemeetagain** [comment]
Yeah, the main difference between the lodestar monorepo and this is that ssz uses independent versioning.
So likely tagging, changelog management, github releases will have to managed differently than lodestar.

Tags will probably look like: ${packageName}@${packageVersion}
Changelogs will either need to be separated by package name in a single file or separated by package directory
Github releases should probably happen for each package release (or maybe just have a github release for the ssz package).

I think ideally all versioning/changelog/github releasing can be handled by lerna. `lerna version` to increment versions + git tag + generate changelog as needed. `lerna publish` to publish versions to npm.

**Comment by g11tech** [comment]
@wemeetagain lerna publish seemed to version and push to git (origin) as well as i ran `yarn lerna publish patch    --skip-npm` and it created and published tags and changelog in my account's forked ssz repo.
(`yarn lerna publish from-package   --skip-npm` was publishing null versions because i guess skip npm was not allowing it to fetch versions)

![image](https://user-images.githubusercontent.com/76567250/135426242-7035877c-a9e1-4b00-93d2-8f2280b2b384.png)

lerna publish seems to be doing bot `lerna version` and publishing, tagging pushing tags and creating release

**Comment by g11tech** [comment]
also doing a full test release on my account's forked repo, the lerna seems to be asking to configure user.email, user.name:

![image](https://user-images.githubusercontent.com/76567250/135449752-ccb11e03-a864-4df0-afe2-4b23267f531d.png)

once i also added that in my repo's release,yml, things finally worked out (with `lerna publish patch --yes --no-verify-access --skip-npm`)

![image](https://user-images.githubusercontent.com/76567250/135449999-d556d7b4-7ff6-4e80-a709-e6a85c03559a.png)

**Comment by g11tech** [comment]
added the missing steps: using the last commits author to prepare release. 

updated PR: https://github.com/ChainSafe/ssz/pull/204/

I think this release workflow is ready to be tested (again) on main ssz repo since all parts minus the actual npm publish have sort of been tested

**Comment by g11tech** [comment]
@wemeetagain I was still playing around a bit and discovered various issues:

1. with the lerna versioning etc (did `lerna version minor` on my local with remote to my account's forked ssz repo), i discovered another issue, look at this published release on my forked repo


https://github.com/g11tech/ssz/releases/tag/%40chainsafe%2Fpersistent-ts%400.20.0

the changelog **0.20.0 (2021-10-01)** created by lerna seems to be linkining to `cronokirby/persistent-ts`
https://github.com/cronokirby/persistent-ts/compare/@chainsafe/persistent-ts@0.19.34...@chainsafe/persistent-ts@0.20.0
have no idea where this is coming from.

also other changelinks links look to be generated hardcoded, one will need to fix the links before submitting for merge etc.
so lerna tool might need some inspection/fixing.
2. If we are publishing a release, we need to mandatory publish releases for all packages which also have git updates since last release. problem is we might not be ready to push their updates. This being an independent repo with --conventional-commits option will not allow us to put a hold onto versions of some packages while publishing others.

3. Changelog generation/added into each repo doesn't look sufficient and the tag compare based changelog has the commits interleaved with other packages.

Already have dug quite a bit into `@lerna/version`. It can be improved quite a bit (and even we can even make it use the packages/*/package.json 's unpublished version to tag, commit  etc) if we are open to patching its versioning.

let know your thoughts on the above.
thanks

**Comment by g11tech** [comment]
Closing it out, as bit more familiar with lerna version behavior.
