### ISSUE TITLE
Update auto-release CI

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/ssz#256]
**Is your feature request related to a problem? Please describe.**

We'd like to streamline our release process to avoid manual bumping of versions and publishing.

**Describe the solution you'd like**

- See the setup in https://github.com/chainsafe/filsnap
They use the google release-please bot to build "Release" PRs which, when merged, trigger the release process.
Unpublished PRs get auto-added to the release PR, and changelogs / github releases are autogenerated from the PR titles.

**Describe alternatives you've considered**

- The setup that we currently have: manually bump versions in package.jsons, CI detects changes and publishes a new release.

- The libp2p setup: After every PR merged, a bot bumps the version and commits to master and publishes a new release.

**Comment by philknows** [comment]
We have release-please
