### ISSUE TITLE
Use little Endian instead of big endian for ByteVectors, or make large disclaimer otherwise

### ISSUE THREAD

**Issue by jonathanpwang** [ChainSafe/ssz#261]
Consensus spec uses little Endian for ByteVectors, but this package still uses big Endian. There is no disclaimer that this package no longer follows the consensus spec.

Steps to reproduce: 

Apply toJson and fromJson to any container and look at Byte array.

**Comment by dapplion** [comment]
Hey @jonathanpwang , thanks for raising this issue. Current master passes all spec tests regarding ssz, both general ssz and each fork static ssz tests (ref https://github.com/ChainSafe/ssz/blob/master/packages/ssz/test/spec/ssz_static.ts)

Would you mind sharing a gist or minimal reproducible case to show the spec divergence?

**Comment by jonathanpwang** [comment]
Hi @dapplion, thanks for the reply. I agree that the package still passes the ssz tests. My issue is more about documentation/clarity for internal usage:

If all types are imported from hex via `type.fromJson()` then there is no problem since that converts a hex number into a ByteVector in Big Endian format. However I wanted to perform some operations on the ByteVector and that required knowing if it was in Big Endian format or Little Endian format. In https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#misc it says the `ENDIANNESS` should be `little`, but after trial and error I determined that it is `big` in your source code. (Extra confusing due to this pull request: https://github.com/ChainSafe/ssz-js/pull/25) 

To reproduce: 
```
import { ContainerType, ByteVectorType } from "@chainsafe/ssz";

const Test = new ContainerType({
  root: new ByteVectorType(2),
});
let type = Test.fromJson(JSON.parse('{ "root": "0x1100"}'));
console.log(type.root);
```

Returns `Uint8Array(2) [ 17, 0 ]` which indicates big Endian; in little Endian it would be `Uint8Array(2) [ 0, 17 ]`. 

Perhaps it does not warrant changing all code to little Endian, but it would be very helpful for external users if the documentation explicitly said somewhere which Endian-ness was used in the source.

**Comment by dapplion** [comment]
Excuse me if I don't follow but for consensus datastructures byte arrays are transparently circulated around without reversing the bytes based on the os endianness. It's up to you as a consumer of the serialization protocol to apply meaning to those bytes including endianness.

**Comment by tuyennhv** [comment]
> Returns Uint8Array(2) [ 17, 0 ] which indicates big Endian; in little Endian it would be Uint8Array(2) [ 0, 17 ].

I think `Uint8Array(2) [ 17, 0 ]` is little endian, refer to https://en.wikipedia.org/wiki/Endianness : "A little-endian system, in contrast, stores the least-significant byte at the smallest address"

I think there is no issue here, the naming of "little endian" is quite confusing since `Little endian machine: Stores data little-end first` https://betterexplained.com/articles/understanding-big-and-little-endian-byte-order/

**Comment by jonathanpwang** [comment]
The least significant byte of `0x1100` is `00`, so in little Endian it should be at array index `0`. This agrees with both links you included. 

Endianness is not decided by the OS; it is decided by the developer. So as the consumer I need to know which endianness the protocol is using to input in data correctly.

**Comment by tuyennhv** [comment]
oh got your point @jonathanpwang . I think `ByteVectorType` is all about an array of byte, there's nothing to do with little endian or big endian here, in the implementation we just convert the hex string to an array of byte and it's a 1-1 mapping, https://github.com/ChainSafe/ssz/blob/master/packages/ssz/src/util/byteArray.ts#L17 , this is very similar to `Buffer.from("1100", "hex")` which we don't specify endianness here

I think the real deal for endianness would be to serialize a number to a byte array and deserialize it back, we can try that with `UintNumberType` type, could you try with an example of that type?

**Comment by wemeetagain** [comment]
I think this could/should be addressed at the spec level if it's an issue.
As I read it in the spec, the only thing thats defined as "little-endian" is [serialization of uints](https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md#uintn)
