### ISSUE TITLE
as-sha256: support totalLength parameter

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/ssz#276]
**Is your feature request related to a problem? Please describe.**

Some consumers only want first n bytes after calling `digest()` and they have to use this pattern: `digest(something).slice(0, n)`, note that `Uint8Array.slice()` returns a copy of the array so it's not efficient

**Describe the solution you'd like**

Add an optional `totalLength` parameter to `digest()` methods so it requires only 1 memory allocation

**Comment by wemeetagain** [comment]
I don't think this is necessary since `Uint8Array.subarray` is also available.
