### ISSUE TITLE
Add Optional type

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/ssz#308]
See https://eips.ethereum.org/EIPS/eip-6475

Used by Verge spec feature https://github.com/ethereum/consensus-specs/pull/3230/files#diff-96e72ffddefb3d85f86dd7cb9f7a75defae9a226db75353b2e2b5b4a01ef685dR117

**Comment by nflaig** [comment]
assign me

**Comment by nflaig** [comment]
@jflo currently not working on this, feel free to open a PR

**Comment by nflaig** [comment]
Related spec update https://github.com/ethereum/consensus-specs/pull/3336

**Comment by etan-status** [comment]
Note: It is still being discussed whether `Optional` will be more optimized, or whether it will just be a type alias for `Union`. See https://ethereum-magicians.org/t/eip-6475-ssz-optional/12891

**Comment by nflaig** [comment]
Resolved by https://github.com/ChainSafe/ssz/pull/329

**Comment by draghtnight** [comment]
> See https://eips.ethereum.org/EIPS/eip-6475
> 
> 
> 
> Used by Verge spec feature https://github.com/ethereum/consensus-specs/pull/3230/files#diff-96e72ffddefb3d85f86dd7cb9f7a75defae9a226db75353b2e2b5b4a01ef685dR117
