### ISSUE TITLE
Unable to use @chainsafe/as-sha256 in a chrome extension

### ISSUE THREAD

**Issue by richtera** [ChainSafe/ssz#312]
The wasm is loaded using new Module() instead of required. This cannot be supported in a manifest 3 chrome extension since it requires wasm-unsafe-eval in the CSP and this is disallowed by chrome. It turns out the latest version of `@ethereumjs/util` can no longer be used in a browser extension due to this. Not sure what the right thing is to do.

**Expected behavior**

Should work normally

**Steps to Reproduce**

Build webextension and require latest versions of `@ethereumjs/util` using webpack

**Screenshots**

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/708186/224988137-41e69b23-da55-4943-b27f-9a86d16b3411.png">

**Desktop (please complete the following information):**

- OS: Mac OS Ventura 13.2.1 (22D68)
- Version:  ^0.3.1
- Branch: master
- Commit hash: ?

**Comment by richtera** [comment]
Ref https://github.com/ethereumjs/ethereumjs-monorepo/issues/2587

**Comment by meeh0w** [comment]
Encountered the very same issue today.

**Comment by nazarhussain** [comment]
As per the manifest [docs](https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/#extension-pages-policy) the `wasm-unsafe-eval` is allowed in the CSP for manifest v3. 

```json
{
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';"
  }
}
```

Could you try that?  If it does not work, Would be very helpful if you spin up a github repo with required and minimum extension setup to reproduce this issue.

**Comment by richtera** [comment]
I got an error when trying that and I using the package inside of the background worker anyways.

**Comment by nazarhussain** [comment]
Can you setup some dummy repo with the extension setup you are trying, that will be helpful to debug the issue and test few things there.

**Comment by meeh0w** [comment]
@nazarhussain Thanks, that works as well! I tried adding `wasm-eval` and `unsafe-eval`, but not `wasm-unsafe-eval` - I didn't know about it up until now.

I'll still have to discuss with my team if we want to add such a directive; it may be okay as a workaround for us.

**Comment by paulmillr** [comment]
@nazarhussain there should be an ability to plug-in a different sha256 implementation, such as noble-hashes. They aren't much slower - the speed is pretty huge.

**Comment by richtera** [comment]
Wouldn't it possible to just require the wasm through a .wasm file rather than unsafe eval it through new Module()?

**Comment by paulmillr** [comment]
Please see this https://github.com/ChainSafe/ssz/issues/313
