### ISSUE TITLE
Broken build due to conflict @types/react

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/ssz#331]
**Describe the bug**

I got this error in my local environment although I used the "--immutable" flag:

```
../../node_modules/@types/react/index.d.ts:3097:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

3097         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/@types/react-alert/node_modules/@types/react/ts5.0/index.d.ts:3208:14
    3208         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.


Found 180 errors.
```

With that flag, it still mutates the yarn.lock file and from there I think there are different versions of @types/react and it causes the issue

**Expected behavior**

No build error

**Comment by mpetrunic** [comment]
@tuyennhv You should check your yarn version locally. It could be that you have somehow overridden node provided yarn version with older 1.x

**Comment by tuyennhv** [comment]
was able to build with `corepack enable` first, thanks @mpetrunic
