### ISSUE TITLE
Add Deneb Fork on simpleserialize.com

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/ssz#346]
**Is your feature request related to a problem? Please describe.**

SimpleSerialize.com currently only contains forks of phase0, altair, bellatrix and capella.

**Describe the solution you'd like**

The site should now also support deneb fork as Mainnet fork happens on the 2024-03-13 13:55:35 UTC and SSZ types are final.

See prev PR https://github.com/ChainSafe/ssz/pull/321

**Comment by philknows** [comment]
Closed via #362
