### ISSUE TITLE
Generating proofs from `BeaconState` object generates OOM errors

### ISSUE THREAD

**Issue by acolytec3** [ChainSafe/ssz#387]
**Describe the bug**

I'm working to build proofs of the `historicalSummaries` property of the `ssz.deneb.BeaconState` object and Node crashes trying to generate the proof with out of memory errors unless I allocate large sections of memory to the script (took 8GB for it not to crash for me).

**Expected behavior**

I should be able to generate proofs of leaf values from the `BeaconState` object without having to allocate large swathes of memory in order to do so. 

**Steps to Reproduce**

Execute this script 
```
import { Tree } from '@chainsafe/persistent-merkle-tree'
import { ssz } from '@lodestar/types'
import { readFileSync } from 'fs'

const data = readFileSync('./test/networks/history/testData/beaconHead.ssz')
const headState = ssz.deneb.BeaconState.deserialize(data)
const gindex = ssz.deneb.BeaconState.getPathInfo(['historicalSummaries'])
const proof = new Tree(ssz.deneb.BeaconState.toView(headState).node).getSingleProof(gindex.gindex)
console.log(proof)
```

See errors like:
![image](https://github.com/user-attachments/assets/3f2636d6-5362-4b71-b5be-77f5df99f5cd)

Running the same script with `NODE_OPTIONS='--max-old-space-size=8192' set allows the script to execute successfully.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 22.04
- Branch: master
- Commit hash: 9889e7ad5a6d5449548f0ead966bf7c1dac2d822 / v0.15.1 that's included in `@lodestar/types@1.18.1`

Note, I'm running on an LG Gram laptop with 16GB ram and a relatively modern 4 core intel i7 CPU so it doesn't seem like this is an issue specifically related to low spec hardware.

**Comment by twoeths** [comment]
@acolytec3 you should be able to deserialize to a Tree without getting through vanilla BeaconState object (which takes a lot of memory)

could you try

```typescript
const stateView = ssz.deneb.BeaconState.deserializeToViewDU(stateBytes);
const proof = new Tree(stateView.node).getSingleProof(gindex.gindex)
```

**Comment by acolytec3** [comment]
Can confirm that this does work without OOM errors now.  Thank you!
