### ISSUE TITLE
Create new type root "SSZType"

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/ssz#4]
I would suggest creating new interface "SSZType" with following properties:
- BasicType and Container type should extend from it
- should contain all common ssz methods like
   - hashTreeRoot
   - serialize
   - deserialize
   - fromJson

This would help with writing generic code that requies any ssz type.

**Comment by wemeetagain** [comment]
I believe we already have a situation like this:

We have the `Type` type which is `BasicType | CompositeType`.
And both `BasicType` and `CompositeType` have the those methods, `hashTreeRoot`, `serialize`, `deserialize`, `fromJson`, `toJson`

**Comment by mpetrunic** [comment]
True, couldn't find it for some reason. I've also encountered issue with unknown and CompositeType, need to investigate it more
