### ISSUE TITLE
Container Representation [Fields as an Array]

### ISSUE THREAD

**Issue by SilentCicero** [ChainSafe/ssz#68]
```
import {ContainerType, ByteVectorType} from "@chainsafe/ssz";

// Creates a "Keypair" SSZ data type (a private key of 32 bytes, a public key of 48 bytes)
const Keypair = new ContainerType({
  fields: {
    priv: new ByteVectorType({
      length: 32,
    }),
    pub: new ByteVectorType({
      length: 48,
    }),
  },
});
```

First off, happy holidays.

Second, does the ContainerType have plans to support the `fields` property as an array. I though properties of containers had to be in specific ordering, and thus an `object` which is non-deterministic or not always deterministically ordered (see: https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) I thought, would not be appropriate.

Wouldn't this be more appropriate?

```
const Keypair = new ContainerType({
  fields: [
    { name: 'priv', value: new ByteVectorType({
      length: 32,
    }) },
    { name: 'pub', value: new ByteVectorType({
      length: 48,
    }) },
  ],
});
```

**Comment by dapplion** [comment]
I think that all recent engines of Javascript do respect insertion order. Using an object lets you have some nice static typing properties which an object form won't allow. Curious to know other's opinions too

**Comment by SilentCicero** [comment]
My only concern is, we are assuming this property and on older engines this
might not be the case. Might want add some CI testing and engine minimum
requirements. Many people still use node10 for example, so it would be good
to know the tests pass on node 10.

These things can cause chaos if not tested or at least constrained.

Anyway, just a thought.

**Comment by dapplion** [comment]
V8 should guarantee insertion order on all versions, I haven't found a case where it doesn't

**Comment by philknows** [comment]
Closing as JS engines have caught up.
