### ISSUE TITLE
Please, update documentation or provide me with some examples of how to unserialize

### ISSUE THREAD

**Issue by olelis** [ChainSafe/ssz#70]
I need to somehow convert aggregation bits from hex-string format to any other format (preferable array of bits or similar)

However, I can't find a documentation how to do that.

Example:
`0x00000004810000001c8114004100002012`
(this is aggregation bits of attestation of a slot in mainnet)

should be converted to this:
[ 0 0 0 100 10000001 0 0 0 11100 10000001 10100 0 1000001 0 0 100000 10]

I have already tried to use BitListType in different ways, however it does not help.

Can you give me more examples how to use this library?

**Comment by wemeetagain** [comment]
You can use the `@chainsafe/lodestar-config` library, it has all the ssz types built for mainnet.
```js
const {config} = require('@chainsafe/lodestar-config/mainnet')

const bits = config.types.CommitteeBits.fromJson('0x00000004810000001c8114004100002012')
// bits = [false, false, false, false, ...]
```

**Comment by olelis** [comment]
@wemeetagain 
Thank you, that helped a lot.
